<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cart_card-img-top product-img</name>
   <tag></tag>
   <elementGuidId>03fbea47-fc00-4d42-ba8d-a643b5450980</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='product1']/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top.product-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.card > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8eefaad-2fd2-44a3-9189-099f2628a6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../pic/pink_shoe.jpg</value>
      <webElementGuid>eefb9294-bef1-4d12-98b2-5f3253b895b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top product-img</value>
      <webElementGuid>34b32e9a-0471-4976-8e64-04e28b4e6143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Adidas Shoe</value>
      <webElementGuid>0a01175c-2ac8-4cdc-be1c-3185ea1b8934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product1&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-lg-3 col-sm-2 col-6&quot;]/div[@class=&quot;card product-card&quot;]/a[1]/img[@class=&quot;card-img-top product-img&quot;]</value>
      <webElementGuid>0069750a-adee-4a4b-8ffc-2753730d5dc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='product1']/div/div/div/div/a/img</value>
      <webElementGuid>a6ac29b4-8fad-49df-9659-86561437e532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Adidas Shoe']</value>
      <webElementGuid>fbb5c5da-e607-4cad-bcbb-e7e029072fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d4cd68b9-ca64-49d2-88f9-006c8f2f6bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../pic/pink_shoe.jpg' and @alt = 'Adidas Shoe']</value>
      <webElementGuid>ed378cad-f822-4a90-bbe4-c40ba0c29ee1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
